# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: billetera.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='billetera.proto',
  package='billetera',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.RetroShop.billeteraB\016billeteraProtoP\001\242\002\003BIP',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x62illetera.proto\x12\tbilletera\"!\n\x0csaldoRequest\x12\x11\n\tidUsuario\x18\x01 \x01(\x05\"\x1e\n\rsaldoResponse\x12\r\n\x05saldo\x18\x01 \x01(\x01\"J\n\x12\x63\x61rgarSaldoRequest\x12\x11\n\tidUsuario\x18\x01 \x01(\x05\x12\x0f\n\x07importe\x18\x02 \x01(\x01\x12\x10\n\x08idSesion\x18\x03 \x01(\x05\"=\n\x17puedeHacerCompraRequest\x12\x11\n\tidUsuario\x18\x01 \x01(\x05\x12\x0f\n\x07importe\x18\x02 \x01(\x01\"4\n\x18puedeHacerCompraResponse\x12\x18\n\x10puedeHacerCompra\x18\x01 \x01(\x08\"N\n\x12hacerCompraRequest\x12\x13\n\x0bidComprador\x18\x01 \x01(\x05\x12\x12\n\nidVendedor\x18\x02 \x01(\x05\x12\x0f\n\x07importe\x18\x03 \x01(\x01\"\x07\n\x05\x45mpty2\xa7\x02\n\tBilletera\x12=\n\x08getSaldo\x12\x17.billetera.saldoRequest\x1a\x18.billetera.saldoResponse\x12>\n\x0b\x63\x61rgarSaldo\x12\x1d.billetera.cargarSaldoRequest\x1a\x10.billetera.Empty\x12[\n\x10puedeHacerCompra\x12\".billetera.puedeHacerCompraRequest\x1a#.billetera.puedeHacerCompraResponse\x12>\n\x0bhacerCompra\x12\x1d.billetera.hacerCompraRequest\x1a\x10.billetera.EmptyB5\n\x1bio.grpc.RetroShop.billeteraB\x0e\x62illeteraProtoP\x01\xa2\x02\x03\x42IPb\x06proto3'
)




_SALDOREQUEST = _descriptor.Descriptor(
  name='saldoRequest',
  full_name='billetera.saldoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idUsuario', full_name='billetera.saldoRequest.idUsuario', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=63,
)


_SALDORESPONSE = _descriptor.Descriptor(
  name='saldoResponse',
  full_name='billetera.saldoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='saldo', full_name='billetera.saldoResponse.saldo', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=95,
)


_CARGARSALDOREQUEST = _descriptor.Descriptor(
  name='cargarSaldoRequest',
  full_name='billetera.cargarSaldoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idUsuario', full_name='billetera.cargarSaldoRequest.idUsuario', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='importe', full_name='billetera.cargarSaldoRequest.importe', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='idSesion', full_name='billetera.cargarSaldoRequest.idSesion', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=171,
)


_PUEDEHACERCOMPRAREQUEST = _descriptor.Descriptor(
  name='puedeHacerCompraRequest',
  full_name='billetera.puedeHacerCompraRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idUsuario', full_name='billetera.puedeHacerCompraRequest.idUsuario', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='importe', full_name='billetera.puedeHacerCompraRequest.importe', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=234,
)


_PUEDEHACERCOMPRARESPONSE = _descriptor.Descriptor(
  name='puedeHacerCompraResponse',
  full_name='billetera.puedeHacerCompraResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='puedeHacerCompra', full_name='billetera.puedeHacerCompraResponse.puedeHacerCompra', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=288,
)


_HACERCOMPRAREQUEST = _descriptor.Descriptor(
  name='hacerCompraRequest',
  full_name='billetera.hacerCompraRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idComprador', full_name='billetera.hacerCompraRequest.idComprador', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='idVendedor', full_name='billetera.hacerCompraRequest.idVendedor', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='importe', full_name='billetera.hacerCompraRequest.importe', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=368,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='billetera.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=377,
)

DESCRIPTOR.message_types_by_name['saldoRequest'] = _SALDOREQUEST
DESCRIPTOR.message_types_by_name['saldoResponse'] = _SALDORESPONSE
DESCRIPTOR.message_types_by_name['cargarSaldoRequest'] = _CARGARSALDOREQUEST
DESCRIPTOR.message_types_by_name['puedeHacerCompraRequest'] = _PUEDEHACERCOMPRAREQUEST
DESCRIPTOR.message_types_by_name['puedeHacerCompraResponse'] = _PUEDEHACERCOMPRARESPONSE
DESCRIPTOR.message_types_by_name['hacerCompraRequest'] = _HACERCOMPRAREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

saldoRequest = _reflection.GeneratedProtocolMessageType('saldoRequest', (_message.Message,), {
  'DESCRIPTOR' : _SALDOREQUEST,
  '__module__' : 'billetera_pb2'
  # @@protoc_insertion_point(class_scope:billetera.saldoRequest)
  })
_sym_db.RegisterMessage(saldoRequest)

saldoResponse = _reflection.GeneratedProtocolMessageType('saldoResponse', (_message.Message,), {
  'DESCRIPTOR' : _SALDORESPONSE,
  '__module__' : 'billetera_pb2'
  # @@protoc_insertion_point(class_scope:billetera.saldoResponse)
  })
_sym_db.RegisterMessage(saldoResponse)

cargarSaldoRequest = _reflection.GeneratedProtocolMessageType('cargarSaldoRequest', (_message.Message,), {
  'DESCRIPTOR' : _CARGARSALDOREQUEST,
  '__module__' : 'billetera_pb2'
  # @@protoc_insertion_point(class_scope:billetera.cargarSaldoRequest)
  })
_sym_db.RegisterMessage(cargarSaldoRequest)

puedeHacerCompraRequest = _reflection.GeneratedProtocolMessageType('puedeHacerCompraRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUEDEHACERCOMPRAREQUEST,
  '__module__' : 'billetera_pb2'
  # @@protoc_insertion_point(class_scope:billetera.puedeHacerCompraRequest)
  })
_sym_db.RegisterMessage(puedeHacerCompraRequest)

puedeHacerCompraResponse = _reflection.GeneratedProtocolMessageType('puedeHacerCompraResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUEDEHACERCOMPRARESPONSE,
  '__module__' : 'billetera_pb2'
  # @@protoc_insertion_point(class_scope:billetera.puedeHacerCompraResponse)
  })
_sym_db.RegisterMessage(puedeHacerCompraResponse)

hacerCompraRequest = _reflection.GeneratedProtocolMessageType('hacerCompraRequest', (_message.Message,), {
  'DESCRIPTOR' : _HACERCOMPRAREQUEST,
  '__module__' : 'billetera_pb2'
  # @@protoc_insertion_point(class_scope:billetera.hacerCompraRequest)
  })
_sym_db.RegisterMessage(hacerCompraRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'billetera_pb2'
  # @@protoc_insertion_point(class_scope:billetera.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_BILLETERA = _descriptor.ServiceDescriptor(
  name='Billetera',
  full_name='billetera.Billetera',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=380,
  serialized_end=675,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSaldo',
    full_name='billetera.Billetera.getSaldo',
    index=0,
    containing_service=None,
    input_type=_SALDOREQUEST,
    output_type=_SALDORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='cargarSaldo',
    full_name='billetera.Billetera.cargarSaldo',
    index=1,
    containing_service=None,
    input_type=_CARGARSALDOREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='puedeHacerCompra',
    full_name='billetera.Billetera.puedeHacerCompra',
    index=2,
    containing_service=None,
    input_type=_PUEDEHACERCOMPRAREQUEST,
    output_type=_PUEDEHACERCOMPRARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='hacerCompra',
    full_name='billetera.Billetera.hacerCompra',
    index=3,
    containing_service=None,
    input_type=_HACERCOMPRAREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BILLETERA)

DESCRIPTOR.services_by_name['Billetera'] = _BILLETERA

# @@protoc_insertion_point(module_scope)
