# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usuario.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='usuario.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rusuario.proto\"R\n\x07Persona\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08\x61pellido\x18\x03 \x01(\t\x12\x0b\n\x03\x64ni\x18\x04 \x01(\x05\x12\x0c\n\x04mail\x18\x05 \x01(\t\"1\n\x06\x43uenta\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x16\n\x0ehashedPassword\x18\x02 \x01(\t\"I\n\x13\x43rearUsuarioRequest\x12\x19\n\x07persona\x18\x01 \x01(\x0b\x32\x08.Persona\x12\x17\n\x06\x63uenta\x18\x02 \x01(\x0b\x32\x07.Cuenta\"\x1d\n\x0fUsuarioResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"/\n\x14IniciarSesionRequest\x12\x17\n\x06\x63uenta\x18\x01 \x01(\x0b\x32\x07.Cuenta\"\x1f\n\x11GetUsuarioRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"/\n\x12GetPersonaResponse\x12\x19\n\x07persona\x18\x01 \x01(\x0b\x32\x08.Persona2\xb2\x01\n\x07Usuario\x12\x36\n\x0cNuevoUsuario\x12\x14.CrearUsuarioRequest\x1a\x10.UsuarioResponse\x12\x38\n\rUsuarioSesion\x12\x15.IniciarSesionRequest\x1a\x10.UsuarioResponse\x12\x35\n\nGetUsuario\x12\x12.GetUsuarioRequest\x1a\x13.GetPersonaResponseb\x06proto3'
)




_PERSONA = _descriptor.Descriptor(
  name='Persona',
  full_name='Persona',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Persona.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombre', full_name='Persona.nombre', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apellido', full_name='Persona.apellido', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dni', full_name='Persona.dni', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mail', full_name='Persona.mail', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=99,
)


_CUENTA = _descriptor.Descriptor(
  name='Cuenta',
  full_name='Cuenta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuario', full_name='Cuenta.usuario', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hashedPassword', full_name='Cuenta.hashedPassword', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=150,
)


_CREARUSUARIOREQUEST = _descriptor.Descriptor(
  name='CrearUsuarioRequest',
  full_name='CrearUsuarioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='persona', full_name='CrearUsuarioRequest.persona', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cuenta', full_name='CrearUsuarioRequest.cuenta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=225,
)


_USUARIORESPONSE = _descriptor.Descriptor(
  name='UsuarioResponse',
  full_name='UsuarioResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UsuarioResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=256,
)


_INICIARSESIONREQUEST = _descriptor.Descriptor(
  name='IniciarSesionRequest',
  full_name='IniciarSesionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cuenta', full_name='IniciarSesionRequest.cuenta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=305,
)


_GETUSUARIOREQUEST = _descriptor.Descriptor(
  name='GetUsuarioRequest',
  full_name='GetUsuarioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetUsuarioRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=338,
)


_GETPERSONARESPONSE = _descriptor.Descriptor(
  name='GetPersonaResponse',
  full_name='GetPersonaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='persona', full_name='GetPersonaResponse.persona', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=387,
)

_CREARUSUARIOREQUEST.fields_by_name['persona'].message_type = _PERSONA
_CREARUSUARIOREQUEST.fields_by_name['cuenta'].message_type = _CUENTA
_INICIARSESIONREQUEST.fields_by_name['cuenta'].message_type = _CUENTA
_GETPERSONARESPONSE.fields_by_name['persona'].message_type = _PERSONA
DESCRIPTOR.message_types_by_name['Persona'] = _PERSONA
DESCRIPTOR.message_types_by_name['Cuenta'] = _CUENTA
DESCRIPTOR.message_types_by_name['CrearUsuarioRequest'] = _CREARUSUARIOREQUEST
DESCRIPTOR.message_types_by_name['UsuarioResponse'] = _USUARIORESPONSE
DESCRIPTOR.message_types_by_name['IniciarSesionRequest'] = _INICIARSESIONREQUEST
DESCRIPTOR.message_types_by_name['GetUsuarioRequest'] = _GETUSUARIOREQUEST
DESCRIPTOR.message_types_by_name['GetPersonaResponse'] = _GETPERSONARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Persona = _reflection.GeneratedProtocolMessageType('Persona', (_message.Message,), {
  'DESCRIPTOR' : _PERSONA,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:Persona)
  })
_sym_db.RegisterMessage(Persona)

Cuenta = _reflection.GeneratedProtocolMessageType('Cuenta', (_message.Message,), {
  'DESCRIPTOR' : _CUENTA,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:Cuenta)
  })
_sym_db.RegisterMessage(Cuenta)

CrearUsuarioRequest = _reflection.GeneratedProtocolMessageType('CrearUsuarioRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREARUSUARIOREQUEST,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:CrearUsuarioRequest)
  })
_sym_db.RegisterMessage(CrearUsuarioRequest)

UsuarioResponse = _reflection.GeneratedProtocolMessageType('UsuarioResponse', (_message.Message,), {
  'DESCRIPTOR' : _USUARIORESPONSE,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:UsuarioResponse)
  })
_sym_db.RegisterMessage(UsuarioResponse)

IniciarSesionRequest = _reflection.GeneratedProtocolMessageType('IniciarSesionRequest', (_message.Message,), {
  'DESCRIPTOR' : _INICIARSESIONREQUEST,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:IniciarSesionRequest)
  })
_sym_db.RegisterMessage(IniciarSesionRequest)

GetUsuarioRequest = _reflection.GeneratedProtocolMessageType('GetUsuarioRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSUARIOREQUEST,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:GetUsuarioRequest)
  })
_sym_db.RegisterMessage(GetUsuarioRequest)

GetPersonaResponse = _reflection.GeneratedProtocolMessageType('GetPersonaResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPERSONARESPONSE,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:GetPersonaResponse)
  })
_sym_db.RegisterMessage(GetPersonaResponse)



_USUARIO = _descriptor.ServiceDescriptor(
  name='Usuario',
  full_name='Usuario',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=390,
  serialized_end=568,
  methods=[
  _descriptor.MethodDescriptor(
    name='NuevoUsuario',
    full_name='Usuario.NuevoUsuario',
    index=0,
    containing_service=None,
    input_type=_CREARUSUARIOREQUEST,
    output_type=_USUARIORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UsuarioSesion',
    full_name='Usuario.UsuarioSesion',
    index=1,
    containing_service=None,
    input_type=_INICIARSESIONREQUEST,
    output_type=_USUARIORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUsuario',
    full_name='Usuario.GetUsuario',
    index=2,
    containing_service=None,
    input_type=_GETUSUARIOREQUEST,
    output_type=_GETPERSONARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USUARIO)

DESCRIPTOR.services_by_name['Usuario'] = _USUARIO

# @@protoc_insertion_point(module_scope)
